### ISSUE TITLE
OpenAI-API error: TypeError: fetch failed

### ISSUE THREAD

**Issue by borisrunakov** [matrixgpt/matrix-chatgpt-bot#100] opened 2023-02-08 20:55 UTC
Using docker v.2.2.1 I get : 
```
Feb 08 19:34:52 tilt303 matrix-bot-chatgpt[1447333]: Wed, 08 Feb 2023 19:34:52 GMT [INFO] [index] Bot started!
Feb 08 20:41:48 tilt303 matrix-bot-chatgpt[1447333]: Wed, 08 Feb 2023 20:41:48 GMT [ERROR] [OpenAI-API Error: TypeError: fetch failed]
Feb 08 20:41:48 tilt303 matrix-bot-chatgpt[1447333]: TypeError: Cannot read properties of undefined (reading 'response')
```

**Comment by jcromero** [comment] 2023-02-08 21:30
Duplicate of #95

**Closed by jcromero** 2023-02-08 21:30 UTC
