### ISSUE TITLE
Error since Version 3.1.5 'Failed to deserialize or serialize a JSON value'

### ISSUE THREAD

**Issue by Sofatraining** [matrixgpt/matrix-chatgpt-bot#281] opened 2024-02-23 11:41 UTC
What version are you running:
v3.1.5

What happened:
After updating to 3.1.5 follwoing error occours:

```
2024-02-23T11:35:35.860227067Z You are ChatGPT, a large language model trained by OpenAI.
2024-02-23T11:35:35.860233869Z Current date: February 23, 2024<|im_sep|>
2024-02-23T11:35:35.860240228Z 
2024-02-23T11:35:35.860246794Z 
2024-02-23T11:35:36.054982880Z node:internal/process/promises:289
2024-02-23T11:35:36.055021974Z             triggerUncaughtException(err, true /* fromPromise */);
2024-02-23T11:35:36.055028418Z             ^
2024-02-23T11:35:36.055033907Z 
2024-02-23T11:35:36.055039456Z [Error: Failed to deserialize or serialize a JSON value missing field `version` at line 1 column 6717] {
2024-02-23T11:35:36.055064088Z   code: 'GenericFailure'
2024-02-23T11:35:36.055069672Z }
```

**Comment by bertybuttface** [comment] 2024-02-26 15:29
This is a duplicate of https://github.com/matrixgpt/matrix-chatgpt-bot/issues/245 which is also still open, closing in favour of #245

**Closed by bertybuttface** 2024-02-26 15:29 UTC
