### ISSUE TITLE
Got "Headers Timeout Error"

### ISSUE THREAD

**Issue by Simonmxy** [matrixgpt/matrix-chatgpt-bot#98] opened 2023-02-08 17:12 UTC
Matrix Server:Synapse-py3 1.76
matrix-chatgpt-bot:2.2.0
Evoked chatgpt bot in matrix room a few hours ago and started getting errors like this consistently.
It worked fine before.
What's wrong with this?What should I check?

```
root@ubuntu20:~# docker run -it --env-file=./matrix-chatgpt-bot/.env --name=chatgpt  ghcr.io/matrixgpt/matrix-chatgpt-bot:latest
yarn run v1.22.19
$ node --enable-source-maps dist/index.js
Wed, 08 Feb 2023 16:51:02 GMT [INFO] [index] Starting bot using ChatGPT model text-chat-davinci-002-20221122
Wed, 08 Feb 2023 16:51:02 GMT [INFO] [index] Bot started!
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:12789:11)
    at <anonymous> (/usr/src/app/node_modules/chatgpt/src/chatgpt-api.ts:235:25) {
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as _onTimeout] (node:internal/deps/undici/undici:9457:32)
      at listOnTimeout (node:internal/timers:570:11)
      at process.processTimers (node:internal/timers:511:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}
```
My env file:
```
# ChatGPT Settings (required)
# Set the API Key from OpenAI
OPENAI_API_KEY=XXX
# Set the ChatGPT conversation context to 'thread', 'room' or 'both'.
CHATGPT_CONTEXT=thread
# (Optional) Explicitly set the ChatGPT model to be used by the API.
#CHATGPT_MODEL=text-chat-davinci-002-20221122
# (Optional) Explicitly set the prefix sent to model at the beginning of a conversation
CHATGPT_PROMPT_PREFIX=Instructions:\nYou are ChatGPT, a large language model trained by OpenAI.
# (Optional) Set to true if ChatGPT should ignore any messages which are not text
CHATGPT_IGNORE_MEDIA=true
# Set data store settings
KEYV_BACKEND=file
KEYV_URL=
KEYV_BOT_ENCRYPTION=false
KEYV_BOT_STORAGE=true
# Matrix Static Settings (required, see notes)
MATRIX_HOMESERVER_URL=XXX
# With the @ and :DOMAIN, ie @SOMETHING:DOMAIN - Not used if `MATRIX_ACCESS_TOKEN` is set.
MATRIX_BOT_USERNAME=XXX
# Set `MATRIX_BOT_PASSWORD` the bot will print an `MATRIX_ACCESS_TOKEN` to the terminal
MATRIX_ACCESS_TOKEN=XXX
# Not used if `MATRIX_ACCESS_TOKEN` is set.
MATRIX_BOT_PASSWORD=XXX
# Matrix Configurable Settings Defaults (optional)
# Leave prefix blank to reply to all messages
MATRIX_DEFAULT_PREFIX=！
MATRIX_DEFAULT_PREFIX_REPLY=false
# Matrix Access Control (optional)
# Can be set to user:homeserver or a wildcard like :anotherhomeserver.example
MATRIX_BLACKLIST=
# `MATRIX_WHITELIST` is overriden by `MATRIX_BLACKLIST` if they contain same entry
MATRIX_WHITELIST=XXX
# Matrix Feature Flags (optional)
MATRIX_AUTOJOIN=true
MATRIX_ENCRYPTION=false
# If you turn threads off you will have problems if you don't set CHATGPT_CONTEXT=room
MATRIX_THREADS=true
MATRIX_PREFIX_DM=false
MATRIX_RICH_TEXT=true
```

**Comment by bertybuttface** [comment] 2023-02-08 17:13
Duplicate of https://github.com/matrixgpt/matrix-chatgpt-bot/issues/92

**Closed by bertybuttface** 2023-02-08 17:13 UTC
